/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorRole;

import Business.Departments.Departments;
import Business.Departments.PharmacistDepartment;
import Business.Location.Location;
import Business.Prescription.Prescription;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PharmacistWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.apache.log4j.Logger;

/**
 *
 * @author Jyoti
 */
public class PrescriptionJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PrescriptionJPanel
     */
    Logger logger = Logger.getLogger(PrescriptionJPanel.class);
    
    private JPanel userProcessContainer;
    private WorkRequest request;
    private UserAccount account;
    private Location enterprise;

    public PrescriptionJPanel(JPanel userProcessContainer, UserAccount account, Location enterprise, WorkRequest request/*, PrescriptionDirectory pDirectory*/) {
        initComponents();
        //this.pDirectory = pDirectory;
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.account = account;
        this.enterprise = enterprise;

        txtPrescptnID.setText(String.valueOf(request.getPrescription().getId()));
        txtDocID.setText(String.valueOf(account.getPerson().getPersonID()));
        txtPatientID.setText(String.valueOf(request.getSender().getPerson().getPersonID()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPrescptnID = new javax.swing.JTextField();
        txtDocID = new javax.swing.JTextField();
        txtPatientID = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        txtAreaDetails = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(220, 226, 235));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setText("Prescription ID");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setText("Doctor ID");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setText("Patient ID");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setText("Details");

        txtPrescptnID.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtPrescptnID.setEnabled(false);

        txtDocID.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtDocID.setEnabled(false);

        txtPatientID.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtPatientID.setEnabled(false);

        btnSend.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnSend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/send-icon.png"))); // NOI18N
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        txtAreaDetails.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        backJButton.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/back-icon.png"))); // NOI18N
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(347, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 238, Short.MAX_VALUE)
                        .addComponent(btnSend))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPatientID)
                            .addComponent(txtDocID)
                            .addComponent(txtPrescptnID, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                            .addComponent(txtAreaDetails))))
                .addGap(334, 334, 334))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPrescptnID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDocID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAreaDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSend)
                    .addComponent(backJButton))
                .addGap(77, 77, 77))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        try {
            //int prescId = Integer.parseInt(txtPrescptnID.getText().trim());
            //int docId = Integer.parseInt(txtDocID.getText().trim());
            int docId = account.getPerson().getPersonID();
            int patientId = Integer.parseInt(txtPatientID.getText().trim());
            String details = txtAreaDetails.getText();

            Prescription p = enterprise.getPrescriptionDirectory().addPrescription();

            p.setPatientId(patientId);
            p.setDoctorId(docId);
            // p.setId(prescId);
            p.setDetails(details);

            request.setPrescription(p);

            JOptionPane.showMessageDialog(null, "Prescription Created Successfully", "Information", JOptionPane.INFORMATION_MESSAGE);
//            txtAreaDetails.setText("");
//            txtDocID.setText("");
//            txtPatientID.setText("");
//            txtPrescptnID.setText("");

            PharmacistWorkRequest pRequest = new PharmacistWorkRequest();
            pRequest.setSender(account);
//        Date date = Calendar.getInstance().getTime();
//        pRequest.setRequestDate(date);
            pRequest.setStatus("Prescribed by Doctor");
            pRequest.setPrescription(p);
            
             logger.info("Prescription created by " + account);

            Departments org = null;
            for (Departments organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (organization instanceof PharmacistDepartment) {
                    org = organization;
                    //System.out.println(organization);
                    break;
                }
            }
            if (org != null) {
                org.getWorkQueue().getWorkRequestList().add(pRequest);
                account.getWorkQueue().getWorkRequestList().add(pRequest);
            }
            
            logger.info("Prescription sent to Pharmacy");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Enter Correct format");
        }
    }//GEN-LAST:event_btnSendActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DoctorWorkAreaJPanel dwjp = (DoctorWorkAreaJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnSend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtAreaDetails;
    private javax.swing.JTextField txtDocID;
    private javax.swing.JTextField txtPatientID;
    private javax.swing.JTextField txtPrescptnID;
    // End of variables declaration//GEN-END:variables
}
